inveniosoftware/invenio-search-js

.travis.yml

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

travis: addition of secured npm api key

---

.travis.yml
deploy.sh

travis: fix typo and authentication

---

package.json

Testing Travis deploy section.

release: v0.0.2

---

example/index.html
src/invenio-search-js/invenioSearchJs.module.js
src/invenio-search-js/templates/invenioSearchResultsPagination.html

* Adds numeric pagination to search results. (closes #9)

directive: addition of numeric pagination

---

package.json

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

release: v0.0.8

---

RELEASE-NOTES.rst

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

release: v0.1.0

---

src/invenio-search-js/invenioSearch.module.js

* FIX Fixes issue with page parameter in initialization. Page parameter
didn't update through the url. (closes #28)

directive: page parameter

---

example/index.html
gulpfile.js
src/invenio-search-js/invenioSearch.module.js
src/invenio-search-js/templates/selectBox.html
src/invenio-search-js/templates/toggleButton.html
test/unit/invenio-search-js/directives/searchSelectBoxSpec.js
test/unit/invenio-search-js/directives/searchSortOrder.js

directive: sort addition

---

src/invenio-search-js/invenioSearch.module.js
src/invenio-search-js/templates/facets.html
test/unit/invenio-search-js/directives/searchFacetsSpec.js

* Adds the functionality to select multiple values for each facet.
(closes #29)

directive: select multiple facets addition

---

src/invenio-search-js/invenioSearch.module.js

* FIX Fixes issue with urls and angular's html5Mode. (closes #40)

global: html5Mode issue with urls

---

src/invenio-search-js/invenioSearch.module.js

* FIX Fixes duplicate request issue on initilization. (closes #42)

directive: initilization request duplication

---

src/invenio-search-js/invenioSearch.module.js
src/invenio-search-js/templates/toggleButton.html
test/unit/invenio-search-js/directives/searchSortOrder.js

* Adds sort order as selectbox.

directive: sort order addition

---

.gitignore
AUTHORS.rst
example/index.html
src/invenio-search-js/invenioSearch.module.js
src/invenio-search-js/templates/error.html
src/invenio-search-js/templates/facets.html
src/invenio-search-js/templates/results.html
src/invenio-search-js/templates/selectBox.html
src/invenio-search-js/templates/toggleButton.html
test/unit/invenio-search-js/controllers/controllersSpec.js
test/unit/invenio-search-js/directives/searchBarSpec.js
test/unit/invenio-search-js/directives/searchErrorSpec.js
test/unit/invenio-search-js/directives/searchFacetsSpec.js
test/unit/invenio-search-js/directives/searchPaginationSpec.js
test/unit/invenio-search-js/directives/searchResultsSpec.js
test/unit/invenio-search-js/directives/searchSelectBoxSpec.js
test/unit/invenio-search-js/directives/searchSortOrder.js

Sorting, double requests and error message fixes

---

RELEASE-NOTES.rst
package.json

release: v0.1.1

---

RELEASE-NOTES.rst
package.json

release: v0.1.2

---

package.json

release: v0.1.3

---

package.json

release: v0.1.4

---

package.json

release: v0.1.5

---

src/invenio-search-js/invenioSearch.module.js
src/invenio-search-js/templates/facets.html
test/unit/invenio-search-js/controllers/controllersSpec.js
test/unit/invenio-search-js/directives/searchErrorSpec.js
test/unit/invenio-search-js/directives/searchFacetsSpec.js
test/unit/invenio-search-js/directives/searchPaginationSpec.js
test/unit/invenio-search-js/directives/searchResultsSpec.js

* FIX Fixes browser's back button and makes sure that the templates are
synchronize with the url's changes. (closes #58)

global: browser back button addition

---

src/invenio-search-js/invenioSearch.module.js

* Adds support for customizing HTTP headers.
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

directive: configurable headers

---

.jshintrc
AUTHORS.rst
example/index.html
example/package.json
karma-src.conf.js
package.json
src/invenio-search-js/invenioSearch.module.js
src/invenio-search-js/templates/facets.html
src/invenio-search-js/templates/range.html
test/unit/invenio-search-js/directives/searchRangeSpec.js

* Adds a directive for filtering a range of items.

directives: number range directive addition

---

RELEASE-NOTES.rst

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

release: v0.2.0

---

example/index.html
src/invenio-search-js/invenioSearch.module.js
src/invenio-search-js/templates/range.html
test/unit/invenio-search-js/directives/searchRangeSpec.js

* Makes text slanted to improve visibility when texts overlap.
* Increases the margin on the selection bar.

directives: make range directive display large ranges better

---

src/invenio-search-js/invenioSearch.module.js

* FIX Fixes errors that occurred when deselecting facets on page change
or when a page with preselected facets have been accessed.
(closes #66) (closes #67) (closes #71)

search: deselection of facet fix

---

RELEASE-NOTES.rst
package.json

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

release: v0.2.1

---

.travis.yml

travis: release on node v6.9.1 LTS

---

.gitignore
.jsdoc
README.md
examples/tutorials/1_started.md
examples/tutorials/2_customize.md
examples/tutorials/tutorials.json
package.json

global: release checklist

---

RELEASE-NOTES.rst
package.json

release: v1.0.0

---

src/invenio-search-js/directives/invenioSearchSelectBox.js
src/invenio-search-js/directives/invenioSearchSortOrder.js
test/unit/invenio-search-js/directives/searchSelectBoxSpec.js
test/unit/invenio-search-js/directives/searchSortOrder.js

* Adds an attribute for a default "sort by" option.
* Handle empty (default) sortKey correctly.

search: default option

---

RELEASE-NOTES.rst
package.json

release: v1.1.0

---

.travis.yml
src/invenio-search-js/controllers/invenioSearchCtrl.js
src/invenio-search-js/directives/invenioSearch.js
test/unit/invenio-search-js/controllers/controllersSpec.js

* Adds the option ``disable-url-handler`` which disables the location
update.

global: addition of disable url update

---

RELEASE-NOTES.rst
package.json

release: v1.1.1

---

examples/simple/index.html
src/invenio-search-js/directives/invenioSearchFacets.js
src/invenio-search-js/templates/facets.html
test/unit/invenio-search-js/directives/searchFacetsSpec.js

* Adds an order attribute for specifying a custom facet order.
(closes #89)

facets: order attribute

---

src/invenio-search-js/controllers/invenioSearchCtrl.js
src/invenio-search-js/directives/invenioSearch.js
src/invenio-search-js/directives/invenioSearchFacets.js

* Fixes the user not being to select another item in a facet when they
follow a URL with a single selection in that facet.
* Fixes a typo.

facets: facet with single selection fix

---

src/invenio-search-js/templates/range.html

Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>

templates: use ng-style instead of inline CSS

---

RELEASE-NOTES.rst
package.json

release: v1.2.0

---

RELEASE-NOTES.rst
package.json
src/invenio-search-js/factories/invenioSearchRangeFactory.js

range: improvment of range user interface

---

examples/simple/index.html
package.json
test/unit/invenio-search-js/directives/searchPaginationSpec.js
test/unit/invenio-search-js/directives/searchResultsSpec.js

installation: upgrade jquery to v3.3.1
